version: '3.8'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - published: 3000
        target: 3000
    volumes:
      - ./client:/app
    depends_on:
      - backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - published: 3001
        target: 3001
    volumes:
      - ./server:/app
    depends_on:
      - database
  database:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    container_name: database
    ports:
      - "1433:1433"
    env_file:
      - ./server/db/sqlserver.env
      - ./server/db/sapassword.env
    volumes:
      - sqlsystem:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
