version: '3.8'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - published: 3000
        target: 3000
    volumes:
      - ./client:/app
    depends_on:
      - backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - published: 3001
        target: 3001
    volumes:
      - ./server:/app
