USE [master]
GO

/****** Object:  Database [WutDoDB]    Script Date: 2/20/2022 8:07:17 PM ******/
CREATE DATABASE [WutDoDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WutDoDB', FILENAME = N'/var/opt/sqlserver/data/WutDoDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WutDoDB_log', FILENAME = N'/var/opt/sqlserver/log/WutDoDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WutDoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WutDoDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WutDoDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WutDoDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WutDoDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WutDoDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [WutDoDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WutDoDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WutDoDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WutDoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WutDoDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WutDoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WutDoDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WutDoDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WutDoDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WutDoDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WutDoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WutDoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WutDoDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WutDoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WutDoDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WutDoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WutDoDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WutDoDB] SET RECOVERY FULL 
GO

ALTER DATABASE [WutDoDB] SET  MULTI_USER 
GO

ALTER DATABASE [WutDoDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WutDoDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WutDoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WutDoDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WutDoDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WutDoDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [WutDoDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [WutDoDB] SET  READ_WRITE 
GO


